version: '3.4'

networks:
  services-network:
    driver: bridge 

services:
  productscategories:
    container_name: productscategories
    image: productscategories:latest
    build:
      context: productscategories
      dockerfile: Dockerfile
    ports:
      - "5050:80"
    networks:
      - services-network
    depends_on:
      - mssql
      - redis

  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: Admin123
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
      MSSQL_TCP_PORT: "1433"
    ports:
      - "1435:1433"
    networks:
      - services-network

  redis:
    container_name: redis
    image: redis
    ports:
      - "5002:6379"
    networks:
      - services-network
